language: java
jdk:
  - oraclejdk8


cache:
  directories:
    - $HOME/.m2

python:
  - "3.4"

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
  - sudo pip3 install azure-cli

script: "az -v"