image: Visual Studio 2017

branches:
  only:
    - master

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"

install:
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"


build_script:
  - mvn -v

after_build:
  - ps: Get-ChildItem -Path . -Recurse -File -Filter *.java | Foreach-Object { Write-Host $_.FullName }
