image: Visual Studio 2017

branches:
  only:
    - master

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"
  
  # 0. share c driver between docker
  - cmd: net share "c=c:"
  # 1. starter docker
  - ps: Start-Process "C:\Program Files\Docker\dockerd.exe"
  # 2. starter emulator docker
  - cmd: docker pull microsoft/azure-cosmosdb-emulator
  - cmd: md %LOCALAPPDATA%\CosmosDBEmulatorCert 2>nul
  - ps: Start-Process "C:\Program Files\Docker\docker.exe" -ArgumentList "run","-v","%LOCALAPPDATA%\CosmosDBEmulatorCert:c:\CosmosDBEmulator\CosmosDBEmulatorCert","-P","-t","-i","microsoft/azure-cosmosdb-emulator" -Wait
  # 3. import cert
  - ps: cd C:\Users\appveyor\AppData\Local\CosmosDBEmulatorCert; .\importcert.ps1
  # 4. export cert to java cert store
  - ps: Get-ChildItem cert:\LocalMachine\My | Format-Table Thumbprint, FriendlyName
  # export cert to Java cert store
  - ps: cd cert:\localmachine\my; Get-ChildItem | Format-Table Thumbprint, FriendlyName; export-Certificate -filepath ${USERPROFILE}\documentdb.cer -cert C8CCE942A1CF161667ED4C034DA36C004B2D0D7C -type CERT -NoClobber
  - cmd: cd "C:\Program Files\Java\jdk1.8.0\jre\lib\security"
  - cmd: certutil "-encode %USERPROFILE%\documentdb.cer documentemulatordb.cer"
  - cmd: keytool -keystore cacerts -importcert -alias documentdbeumlatorcert -file .\documentemulatordb.cer
  
  

build_script:
  - mvn cobertura:cobertura-integration-test -P integration-test-emulator -B -V
