image: Visual Studio 2015

branches:
  only:
    - master

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"

install:
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"
  # Install Cosmos DB Emulator
  - ps: Start-FileDownload 'https://aka.ms/cosmosdb-emulator' -FileName 'C:\Azure Cosmos DB.Emulator.msi'
  - msiexec.exe /i 'C:\Azure Cosmos DB.Emulator.msi' /quiet /qn
  # export cert to Java cert store
  - ps: cd cert:\localmachine\my; export-Certificate -filepath ${USERPROFILE}\documentdb.cer -cert 2c68332f680386788c4a5d5077264bc5a3bc38b9 -type CERT -NoClobber
  - cmd: cd "C:\Program Files\Java\jdk1.8.0\jre\lib\security"
  - cmd: certutil "-encode %USERPROFILE%\documentdb.cer documentemulatordb.cer"
  - cmd: keytool -keystore cacerts -importcert -alias documentdbeumlatorcert -file .\documentemulatordb.cer
  # Start Cosmos DB Emulator
  - ps: >-
      "${env:ProgramFiles}\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe"

build_script:
  - mvn cobertura:cobertura-integration-test -P integration-test-emulator -B -V
