image: Visual Studio 2015

branches:
  only:
    - master

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"

install:
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"
  # Install Cosmos DB Emulator
  - ps: Start-FileDownload 'https://aka.ms/cosmosdb-emulator' -FileName 'C:\AzureCosmosDB.Emulator.msi'
  # - msiexec.exe /i "C:\Azure Cosmos DB.Emulator.msi" /qn
  - ps: Start-Process "msiexec.exe" -ArgumentList "/i","C:\AzureCosmosDB.Emulator.msi","/qn" -Wait
  - cmd: dir "C:\Program Files\Azure Cosmos DB Emulator"
  
  # open 8081 port
  - netsh: advfirewall firewall add rule name="documentdb emulator 8081" dir=in action=allow protocol=TCP localport=8081
  - netsh: advfirewall firewall add rule name="documentdb emulator 8081" dir=out action=allow protocol=TCP localport=8081
  
  - ps: >-
      "${env:ProgramFiles}\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe /noui /Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
  # export cert to Java cert store
  #- ps: cd cert:\localmachine\my; Get-ChildItem | Format-Table Thumbprint, FriendlyName; export-Certificate -filepath ${USERPROFILE}\documentdb.cer -cert 2c68332f680386788c4a5d5077264bc5a3bc38b9 -type CERT -NoClobber
  #- cmd: cd "C:\Program Files\Java\jdk1.8.0\jre\lib\security"
  #- cmd: certutil "-encode %USERPROFILE%\documentdb.cer documentemulatordb.cer"
  #- cmd: keytool -keystore cacerts -importcert -alias documentdbeumlatorcert -file .\documentemulatordb.cer
  - ps: $pass = ConvertTo-SecureString -String "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==" -Force -AsPlainText
  - ps: $cert = Get-ChildItem cert:\LocalMachine\My | Where-Object {$_.FriendlyName -eq "DocumentDbEmulatorCertificate" }
  - ps: $output = Export-PfxCertificate -Cert $cert -FilePath c:\CosmosDBEmulatorCert.pfx
  - ps: $output = Import-PfxCertificate -FilePath .\CosmosDBEmulatorCert.pfx cert:\localMachine\my | Import-PfxCertificate -FilePath .\CosmosDBEmulatorCert.pfx cert:\localMachine\root
  - ps: Get-ChildItem cert:\LocalMachine\My | Format-Table Thumbprint, FriendlyName
  

build_script:
  - mvn cobertura:cobertura-integration-test -P integration-test-emulator -B -V
